#!/bin/bash
set -e

# format shell scripts
shfmt -w -l .
shfmt -w -l immunity-config/files/immunity.agent
shfmt -w -l immunity-config/files/immunity.init

# format lua files
cd immunity-config
lua-format -i --config=luaformat.config \
	files/sbin/*.lua \
	files/lib/immunity/*.lua \
	tests/*.lua
