#!/bin/bash
set -e

# will be 1 by default when run through github actions
CI=${CI:-0}

if [ "$CI" -eq 1 ]; then
	# during github actions CI, copy these files so that they can be checked by
	# the github action step "action-sh-checker" (see .github/workflows/ci.yml)
	cp immunity-config/files/immunity.agent immunity_agent
	cp immunity-config/files/immunity.init immunity_init
else
	# check shell scripts formatting
	sh_files=$(shfmt -f .)
	# shellcheck disable=SC2086
	shellcheck $sh_files \
		immunity-config/files/immunity.agent \
		immunity-config/files/immunity.init

	shfmt -d .
	shfmt -d immunity-config/files/immunity.agent
	shfmt -d immunity-config/files/immunity.init
fi

immunity-qa-check \
	--skip-checkmigrations \
	--skip-isort \
	--skip-flake8 \
	--skip-black
